spring:
  application:
    name: ServerOauth
  ## redis 配置
  redis:
    database: 4
    host: 112.74.43.136
    port: 6379
    password: jingbaobao

server:
  port: 8100

logging.level.org.springframework.security: DEBUG

security:
  oauth2:
    client:
      refresh-token-validity-seconds:  500