spring:
  application:
    name: resouricesOauth
  ## redis 配置
  redis:
    database: 4
    host: 112.74.43.136
    port: 6379
    password: jingbaobao

server:
  port: 8300

security:
  oauth2:
 #   resource:
#      token-info-uri: http://localhost:9005/oauth/check_token
#      user-info-uri: http://localhost:9005/user
   # authorization:
#      check-token-access: http://localhost:9005/oauth/check_token



basic:
  errorUrl:
    unauthorized: http://localhost:8100/error/401
  oauth2:
    authorizationUrl: http://localhost:8100/oauth/token
    clientId: client_2
    secret: 123456
    scope: select






